# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sound', models.FileField(upload_to='upload/sounds')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('sha1', models.CharField(editable=False, max_length=40, unique=True)),
                ('codec', models.CharField(editable=False, max_length=30)),
                ('size', models.IntegerField(editable=False)),
                ('duration', models.FloatField(editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
